drop table if exists accidents;

create table accidents (
    ID varchar(10) primary key,
    Source varchar(10),
    Severity smallint,
    Start_Time text,
    End_Time text,
    Start_Lat float,
    Start_Lng float,
    End_Lat float,
    End_Lng float,
    Distance float,
    Description text,
    Street text,
    City text,
    County text,
    State text,
    Zipcode text,
    Country text,
    Timezone text,
    Airport_Code text,
    Weather_Timestamp text,
    Temperature float,
    Wind_Chill float,
    Humidity float,
    Pressure float,
    Visibility float,
    Wind_Direction text,
    Wind_speed float,
    Precipitation float,
    Weather_Condition text,
    Amenity bool,
    Bump bool,
    Crossing bool,
    Give_Way bool,
    Junction bool,
    No_Exit bool,
    Railway bool,
    Roundabout bool,
    Station bool,
    Stop bool,
    Traffic_Calming bool,
    Traffic_Signal bool,
    Turning_Loop bool,
    Sunrise_Sunset text,
    Civil_Twilight text,
    Nautical_Twilight text,
    Astronomical_Twilight text
);

